[package]
name = "global_lib"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "nodes",
    "interface",
    "ui"
]


[dependencies]
byteorder = "1.4"
tokio = { version = "1.37.0", features = ["full"] }    
rand = "0.8"
serde_json = "1.0.117"
libnotify = "1.0.3"    